import { StyleSheet } from 'react-native';
import theme from '~/styles/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 4,
  },
  productImage: {
    height: 180,
    resizeMode: 'contain',
  },
  productContent: {
    flex: 1,
    padding: 2,
  },
  productName: {
    height: 80,
    borderWidth: 1,
    borderColor: theme.colors.greyBorder,
    borderRadius: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  productNameText: {
    fontSize: 18,
    color: theme.colors.stoke,
  },
  productPrice: {
    padding: 16,
    marginTop: 12,
    width: '100%',
    height: 60,
    borderWidth: 1,
    borderColor: theme.colors.greyBorder,
    borderRadius: 3,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#000',
    flexDirection: 'row',
  },
  productPriceText: {
    fontSize: 19,
    color: theme.colors.stoke,
  },
  productDefaultPrice: {
    color: theme.colors.encarte,
    padding: 2,
    margin: 3,
    fontSize: 19,
  },
  featuredPrice: {
    fontSize: 19,
    padding: 2,
    color: '#ff0000',
    backgroundColor: 'yellow',
    borderRadius: 4,
    margin: 3,
    borderWidth: 1,
    borderColor: '#e3e3e3',
    fontWeight: 'bold',
  },
  specialOfferProductPrice: {
    fontSize: 19,
    color: '#ff0000',
    fontWeight: 'bold',
    padding: 2,
    backgroundColor: 'yellow',
    margin: 3,
    marginLeft: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#e3e3e3',
    textAlign: 'center',
  },
  productDescriptionTitle: {
    marginTop: 10,
    fontWeight: 'bold',
    fontSize: 15,
    color: theme.colors.stoke,
  },
  productDescription: {
    minHeight: 300,
    textAlign: 'left',
    fontSize: 18,
    borderWidth: 1,
    borderColor: theme.colors.greyBorder,
    borderRadius: 3,
    padding: 8,
    marginBottom: 5,
  },
  productDescriptionText: {
    color: theme.colors.stoke,
    fontSize: 16,
  },
  addProduct: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    width: '95%',
    bottom: 10,
    borderWidth: 1,
    borderColor: theme.colors.greyBorder,
    borderRadius: 10,
    height: 60,
    marginTop: 8,
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    color: theme.colors.encarte,
    fontSize: 17,
    alignSelf: 'center',
  },
  amountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  amountInput: {
    width: 50,
    textAlign: 'center',
  },
  total: {
    fontSize: 17,
    textAlign: 'center',
    color: theme.colors.encarte,
  },
  iconColor: {
    color: theme.colors.encarte,
  },
});
